### ISSUE TITLE
Duplicated acf groups

### ISSUE THREAD

**Issue by mnngithub** [FreshFlesh/acf-sync#4]
Hi @thomascharbit 

Most of my acf groups get duplicated when i use the auto sync. The json files are big and may be this parallel sync is causing the process to run multiple times concurrently.

Any idea how to fix this?

**Comment by thomascharbit** [comment]
Hi, i would avoid this plugin now that ACF allows manual sync, it is untested on newer ACF versions and i am not maintaining it anymore.

Do you have a use case for the autosync feature? I am personally not missing this feature at all on my WP projects.

**Comment by mnngithub** [comment]
Hi @thomascharbit 

Yes, i have automated release process, which delivers code changes to staging and production envs to hundreds of sites and going through each and every one of them to manually trigger syncing is not pleasant and feasible task. 

Update: ACF community advised me that if on staging and production i don't sync the groups at all, the fields will be read from the json files directly instead of reading them from the database, so this means that i wouldn't need to sync them at all on staging/production. However this brings the question - is this wise from performance point of view?

**Comment by thomascharbit** [comment]
> ACF community advised me that if on staging and production i don't sync the groups at all, the fields will be read from the json files directly instead of reading them from the database, so this means that i wouldn't need to sync them at all on staging/production.

Exactly, so you don't really need to sync them back into the DB really.

> However this brings the question - is this wise from performance point of view?

Reading JSON files is not the best performance-wise, but this is absolutely not an issue.
Also you can [register your field groups via PHP](https://www.advancedcustomfields.com/resources/register-fields-via-php/) to avoid this.
It also improves readability in commits.
